### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by PrzemoF** [edwardvmills/Silk#1]
Installed by cloning git repo:
`Cannot find icon: /home/przemo/.FreeCAD/Mod/Silk/Resources/Icons\Point_onCurve.svg
Cannot find icon: /home/przemo/.FreeCAD/Mod/Silk/Resources/Icons\SubGrid33_2Grid64.svg`

**Comment by edwardvmills** [comment]
that's a \ versus / problem in the file path. thank you for reporting it. i may not be able to get to it today though. soon, i promise :)

**Comment by edwardvmills** [comment]
i believe the issue should be fixed, but since i'm on windows, i can't see it directly.

**Comment by PrzemoF** [comment]
Fixed.
