### ISSUE TITLE
[Silk] SVG logo that represents this WB

### ISSUE THREAD

**Issue by luzpaz** [edwardvmills/Silk#10]
ref: https://www.freecadweb.org/wiki/Template:DevWorkbenches

**Comment by luzpaz** [comment]
https://github.com/FreeCAD/FreeCAD-addons/issues/37

**Comment by luzpaz** [comment]
@edwardvmills ping

**Comment by edwardvmills** [comment]
i had one in progress, but it was too detailed. i haven't worked on it in a long time.

unfortunately, i have no idea when i'll have time to work on this again...i hope soon.

**Comment by luzpaz** [comment]
can we post a request to the UI/UX forum to see if someone will create one in the meantime ?

**Comment by edwardvmills** [comment]
honestly i'd rather not at this time. it feels kind of personal. as far as i know, no one has reported using the workbench  outside of a few people testing it very early on. now if lots of people were using it, and the lack of icon clarity was causing productivity issues, i suppose i wouldn't stand in the way.

On my computer, the crappy existing icon loads as it is. does it not show up on other people's machines?

like i said, it exists, but it doesn't do a very good job as an icon

`class Silk (Workbench):
	
	def __init__(self):
		self.__class__.Icon = FreeCAD.getUserAppDataDir()+"Mod" + "/Silk/Resources/Icons/Silk.svg"
		self.__class__.MenuText = "Silk"
		self.__class__.ToolTip = "NURBS Surface modeling tools focused on low degree and seam continuity "`

**Comment by edwardvmills** [comment]
https://github.com/edwardvmills/Silk/blob/master/Resources/Icons/Silk.svg

**Comment by edwardvmills** [comment]
it was a bummer when i saw it was an unreadable mess at final size, because i had fun drawing it with the workbench itself. as shown above, a lot intricacies of the design have already been removed, and it still is unreadable as the icon in the workbench drop down

**Comment by edwardvmills** [comment]
i'm trying to read up on 
https://forum.freecadweb.org/viewtopic.php?f=9&t=36556

so i can see what i ought to take of right now.

**Comment by luzpaz** [comment]
no pressure. :)

**Comment by luzpaz** [comment]
@edwardvmills  
How about using the shape in this?  

![example of current capability](https://github.com/edwardvmills/Silk/blob/master/Resources/Demo_files/Silk_Demo_02.png?raw=true)

**Comment by edwardvmills** [comment]
I guess it depends what size you want for the final icon. My previous reference size was the icons in the workbench dropdown menu, and those are tiny.

when you initially posted this thread, where did you envision anyone seeing this icon?

**Comment by luzpaz** [comment]
In the addon manager workbench/addon menu.. right now there is no icon next to your workbench in it.

**Comment by luzpaz** [comment]
![image](https://user-images.githubusercontent.com/4140247/62803197-c47fc480-bab7-11e9-9332-195596426544.png)

**Comment by luzpaz** [comment]
Checkout https://github.com/FreeCAD/FreeCAD/pull/2403

**Comment by luzpaz** [comment]
> I guess it depends what size you want for the final icon. My previous reference size was the icons in the workbench dropdown menu, and those are tiny.

https://github.com/FreeCAD/FreeCAD/tree/master/src/Mod/AddonManager/Resources/icons

**Comment by luzpaz** [comment]
you can scale an svg up or down no problem, so size isn't relevant.

**Comment by edwardvmills** [comment]
i know vector graphics scale, that's not what i'm concerned about. a functional icon should be discernable _at the size it will normally be seen_. if this icon will be seen in in the WB drop down, and the addon manager left side logos, _it needs to communicate something, when seen at that size_ using default application icon size. It just happens to be that in these two instances the icons are displayed _quite small_ by FreeCAD, compared to toolbar icons, for example.

This is just a design challenge. I have a new icon idea, but it's not ready yet.

**Comment by edwardvmills** [comment]
from your linked issue above:
"Will help users understand what the addon does when they browse through the list of addons"
in the case of this workbench, it's a bit of a challenge to communicate something useful....but i have some ideas...it's ready when it's ready :)

**Comment by luzpaz** [comment]
There are several addons that are not discernable by name or logo, so I wouldn't worry about that. It's more about how you structure your README.md page than anything, IMHO. That's what the user is going to go with.

**Comment by luzpaz** [comment]
Any updates ?

**Comment by luzpaz** [comment]
@edwardvmills bump

**Comment by luzpaz** [comment]
@edwardvmills any thoughts on this?

**Comment by luzpaz** [comment]
We'd love to have logo in the Addon Manager and several wiki pages + a dedicated wiki page for this Addon as well ...
so pretty please can you decide on an icon :sweat_smile:

**Comment by edwardvmills** [comment]
ok, i just decided to bite the bullet and remove the text from an existing icon....but i had to download inkscape and i have very slow internet....soon!

thank you for your tenacity.

**Comment by edwardvmills** [comment]
https://github.com/edwardvmills/Silk/blob/master/Resources/Icons/Silk.svg

and

https://github.com/edwardvmills/Silk/blob/master/Resources/Icons/Silk.png

**Comment by luzpaz** [comment]
Just created https://wiki.freecadweb.org/Silk_Workbench
Congrats :smile:

**Comment by edwardvmills** [comment]
Thanks luzpaz!

**Comment by luzpaz** [comment]
Note: I was asked to save the SVG as a Plain SVG, see https://github.com/FreeCAD/FreeCAD/pull/3128#issuecomment-594714414

**Comment by edwardvmills** [comment]
ok, found the relevant option in inkscape. pushed. should be good now
