### ISSUE TITLE
Why is there a submodule of Silk within Silk?

### ISSUE THREAD

**Issue by luzpaz** [edwardvmills/Silk#12]
![image](https://user-images.githubusercontent.com/4140247/61147756-247c4e80-a4ab-11e9-9271-47448fbe5408.png)

**Comment by edwardvmills** [comment]
it's empty. probably created by accident in this location, or moved by accident. will remove

**Comment by luzpaz** [comment]
Thanks, yea, i was getting errors when trying to run a `git pull`

**Comment by edwardvmills** [comment]
did the error prevent you from pulling?

**Comment by edwardvmills** [comment]
crap. got a new computer, pulled and didn't do much for a while. now it's doing something weird with my .gitignore

windows wasn't displaying the .gitgnore file name correctly. tried editing it, and then git  said i had added a new file '.gitignore.gitignore' deleted and recreated .gitignore, but git doe not ignore and tries to pull all the .pyc into the queue.

gonna take me a bit to sort this out

**Comment by edwardvmills** [comment]
yeah, have an OS problem here with .files

`

Untracked files:                                                                          (use "git add ..." to include in what will be committed)                                                                                                                        .gitignore.txt                                                                          ArachNURBS.pyc                                                                          ControlGrid44.pyc                                                                       ControlGrid44_2EdgeSegments.pyc                                                         ControlGrid44_EdgeSegment.pyc                                                           ControlGrid64.pyc                                                                       ControlGrid64_2Grid44.pyc                                                               ControlGrid64_3_1Grid44.pyc                                                             ControlGrid66.pyc                                                                       ControlGrid66_4Sub.pyc                                                                  ControlGridNStar66.pyc                                                                  ControlPoly4.pyc                                                                        ControlPoly4_segment.pyc                                                                ControlPoly6.pyc                                                                        CubicCurve_4.pyc                                                                        CubicCurve_6.pyc                                                                        CubicNStarSurface_NStar66.pyc                                                           CubicSurface_44.pyc                                                                     CubicSurface_64.pyc                                                                     CubicSurface_66.pyc                                                                     Point_onCurve.pyc                                                                       Silk_dummy.pyc                                                                          StarTrim_CubicNStar.pyc                                                                 SubGrid33_2Grid64.pyc                                                                   SubGrid63_2Surf64.pyc                                                                   __pycache__/                                                                                                                                                            no changes added to commit (use "git add" and/or "git commit -a")                                                                                                               Edward Mills@DESKTOP-7C746LP MINGW64 ~/AppData/Roaming/FreeCAD/Mod/Silk (master)        $ git add .gitignore                                                                                                                                                            Edward Mills@DESKTOP-7C746LP MINGW64 ~/AppData/Roaming/FreeCAD/Mod/Silk (master)        $ git add .gitignore                                                                    fatal: pathspec '.gitignore' did not match any files
--


`
git sees gitignore and puts it in untracked files, but if i try to add it, then it can't find it. i'm pretty stumped

**Comment by edwardvmills** [comment]
ok, now i see it. windows is doing weird shit with file extensions.

**Comment by edwardvmills** [comment]
ok, things are looking ok from my end. empty Silk folder removed.
