### ISSUE TITLE
Is Silk ready for FreeCAD 1.0 Release ?

### ISSUE THREAD

**Issue by luzpaz** [edwardvmills/Silk#36]
* https://github.com/FreeCAD/Addons/issues/13

**Comment by edwardvmills** [comment]
Not yet.

Three phases needed:
-a sizable update to complete under 0.2x
-1.0RC testing (not started yet - i can't afford to lose my config files right now...so i must finish the the 0.2x update first)
-light and dark mode issues

If a Silk user could test under RC1.0, that'd be great...but i'll still have to follow the workflow above.

**Comment by luzpaz** [comment]
Any Silk users come to mind that you can ping ?

**Comment by edwardvmills** [comment]
Eventually i might, but i struggle to find any time to work on Silk these days...i really need to focus on the update itself.

Honestly....if you could just load the WB and confirm it doesn't make FreeCAD hang that would be a great first step :)

**Comment by pixelwaster** [comment]
The workbench loads and FreeCAD still works. Not sure on how to use this WB yet, just starting on CAD/CAM.

**Comment by edwardvmills** [comment]
Thanks pixelwaster!

**Comment by luzpaz** [comment]
I can load Silk in  
```
OS: Manjaro Linux (KDE/plasma/xcb)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.39092 (Git) AppImage
Build type: Release
Branch: main
Hash: a65d05c6e495038168eefcba6a1e43218fbb3a20
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * Silk 0.1.5
```

**Comment by edwardvmills** [comment]
Thanks luzpaz. I'm just stuck on work these days. If the WB doesn't hang FreecAD 1.0, i see no reason not to keep it in the addon manager.

I do have work in progress on Silk, but I want to wrap up the changes before moving on to 1.0 myself. Might not happen until winter, when I can finally take some time off.

**Comment by luzpaz** [comment]
Totally understand. Silk is an awesome workbench and it would be a shame for it to fall to the wayside.

**Comment by rmdug** [comment]
Hello,

I can’t install silk on FreeCAD through the addon manager :
« Installation failed »
"Impossible d'installer Silk
Git returned a non-zero exit status: -1
Called with: /usr/bin/git clone --recurse-submodules https://github.com/edwardvmills/Silk /home/rem/.local/share/FreeCAD/Mod/Silk

Returned stderr:
Clonage dans '/home/xxxx/.local/share/FreeCAD/Mod/Silk'...
fatal : fin de fichier prématurée"

OS: Manjaro Linux (KDE/plasma/xcb)
Architecture: x86_64
Version: 1.1.0dev.39748 (Git) Conda AppImage
Build type: Release
Branch: main
Hash: e977eb49e37ef836f695809263fa1f56a17cc657
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: French/Belgium (fr_BE)
Stylesheet/Theme/QtStyle: ProDark.qss/FreeCAD Dark/Qt default
Installed mods: 
  * Render 2024.12.15
  * sheetmetal 0.6.13
  * Curves 0.6.53
  * freecad.gears 1.3.0
  * Silk
  * FreeCAD-themes 2024.7.24
  * GDT
  * fasteners 0.5.34
  * fasteners.backup1735901309.314019 0.5.34 (Disabled)
  * Glass
  * InventorLoader 1.5.1

Yet Silk is shown on the above addon list it doesn’t appear on the actual WB list in FC and thus cannot be launched nor tested.

Regards,

Rémi
