### ISSUE TITLE
Updating Silk WB to be compatible with the upcoming 0.18 release (req. py3 and Qt5 compatibility) 

### ISSUE THREAD

**Issue by luzpaz** [edwardvmills/Silk#7]
ref: https://github.com/FreeCAD/FreeCAD-addons/issues/93

**Comment by edwardvmills** [comment]
Thanks for the heads up Luzpaz. This project is hibernating a bit right now, but i'll do my best to be ready for 0.18 :)

**Comment by luzpaz** [comment]
@edwardvmills just checking in, can I close this ticket ?
