### ISSUE TITLE
Start failture

### ISSUE THREAD

**Issue by brothermechanic** [edwardvmills/Silk#8]
Hello
In my custom build (git  0.18 and 0.17) i get this error
`Missing parentheses in call to 'print'. Did you mean print('curves do not share endpoints')? (ArachNURBS.py, line 108)`
Can you help me to get Silk wirking?
PS: on appimage freecad build all works fine
My libs:
Boost 1_65
Coin3D 4.0.0a
Open CASCADE Technology 7.3.0
Python 3.6.5
Qt 5.11.1
zlib 1.2.11

**Comment by PrzemoF** [comment]
This is python2 vs python3 problem Add () or use python2
'''$ python
Python 2.7.15 (default, May 16 2018, 17:50:09) 
[GCC 8.1.1 20180502 (Red Hat 8.1.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> print 'curves do not share endpoints'
curves do not share endpoints
>>> 

$ python3
Python 3.6.5 (default, Mar 29 2018, 18:20:46) 
[GCC 8.0.1 20180317 (Red Hat 8.0.1-0.19)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> print 'curves do not share endpoints'
  File "<stdin>", line 1
    print 'curves do not share endpoints'
                                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('curves do not share endpoints')?
>>> print('curves do not share endpoints')
curves do not share endpoints
>>>

**Comment by brothermechanic** [comment]
Ok, thank you.
Do you plan updating to python3?

**Comment by edwardvmills** [comment]
yes i do plan on updating, but i have not set myself a timeframe. It might not happen until FreeCAD literally forces me to do so with .18

If you actually use Silk to build a significant body of work, and need Py3 to keep working on it, that would motivate me to get it done sooner.

Personally, professional work is taking all my attention these days. The project is not dead, but not active either.

**Comment by edwardvmills** [comment]
Unrelated topic: there is limited documentation here, but if you search my posts on the FreeCAD forum (emills2) the tools are explained in much greater detail.

**Comment by edwardvmills** [comment]
py3 and print statements fixed a while back
